### ISSUE TITLE
ADD-S and ADD metrics

### ISSUE THREAD

**Issue by YuukkiFu** [lyltc1/HiPose#1]
May I ask if you can provide testing code for ADD-S and ADD metrics on datasets such as LMO and YCB, in addition to BOP scores?

**Comment by lyltc1** [comment]
We apologize for forgetting to provide the code for the ADD-S and ADD metrics. If you are in a hurry, you can refer to this script. However, we cannot guarantee that it will work perfectly, as it is an intermediate version of our developing code. Making small changes to the dataset or network should be sufficient. We will make sure to upload a fully functional script as soon as possible.
[test_with_region_v3.zip](https://github.com/lyltc1/HiPose/files/15130965/test_with_region_v3.zip)

**Comment by lyltc1** [comment]
We apologize for forgetting to provide the code for the ADD-S and ADD metrics. If you are in a hurry, you can refer to this script. However, we cannot guarantee that it will work perfectly, as it is an intermediate version of our developing code. Making small changes to the path of dataset or network should be sufficient. We will upload a fully functional script as soon as possible.

**Comment by YuukkiFu** [comment]
Thanks, I'll try it. Looking forward to seeing the final version you upload as soon as possible!
