### ISSUE TITLE
Detection boxes

### ISSUE THREAD

**Issue by chang2727** [lyltc1/HiPose#5]
When I set BOP challenge to False, my detBox contents are shown in the figure below. It can be seen that some images do not have corresponding detection boxes. Could you provide a complete JSON file of detection boxes for all images in the BOP test, rather than just the detection boxes for images that exist in the BOP19 test set?
![58c959b34f5cb187a384b1c75a1c6a85](https://github.com/user-attachments/assets/f5ae314b-5b13-46cb-ac9a-1909619286bc)

**Comment by lyltc1** [comment]
Hello,

It appears that the BOP challenge does not provide detection boxes for the entire test set. You have two options available:

1. Utilize the FCOS detector, as demonstrated in [fcos_V57eSE_MSx1333_ColorAugAAEWeaker_8e_lmo_pbr.json](https://github.com/lyltc1/HiPose/blob/main/hipose/detection_results/lmo/fcos_V57eSE_MSx1333_ColorAugAAEWeaker_8e_lmo_pbr.json).

2. Generate all the detection boxes yourself using the code available at [https://github.com/shanice-l/gdrnpp_bop2022](https://github.com/shanice-l/gdrnpp_bop2022). Please be aware that this may require some effort to tailor it to your specific needs.

This is the same issue as #3 .

**Comment by chang2727** [comment]
Thank you for your replay
