### ISSUE TITLE
The replication results for the bowl* and wood_block*  are much worse than those in the original paper. 

### ISSUE THREAD

**Issue by YuukkiFu** [lyltc1/HiPose#6]
Hello! I noticed that the replication results for the bowl* and wood_block* objects are much worse than those in the original paper. The wood_block* was trained for 84,000 steps with the best weights saved at 59,000 steps; the bowl* was trained for 198,000 steps with the best weights saved at 136,000 steps. Apart from these two symmetric objects having low accuracy, the accuracy of other symmetric objects is normal. May I ask if you can provide some assistance with this issue? The accuracy comparison is shown in the following figure.
![image](https://github.com/user-attachments/assets/77c0ebc0-83ad-45f8-812e-35f34d0f28a1)

**Comment by lyltc1** [comment]
Hi, I notice that our ckpt for wood_block* object is saved at step 207,000 and bowl* objects is saved at step 214,000. Maybe you will get better result if the training process continues.
