### ISSUE TITLE
How do I train on custom data?

### ISSUE THREAD

**Issue by GavinYang5** [lyltc1/HiPose#7]
How do I train on my dataset and what should I prepare?

**Comment by lyltc1** [comment]
To use our code, you should prepare the dataset according to BOP dataset. Then, the ground truth (xxx_GT) should be generated by yourself according to the instructions provided in the following link: [Generate_GT.md](https://github.com/suyz526/ZebraPose/blob/main/Binary_Code_GT_Generator/Generate_GT.md).

**Comment by GavinYang5** [comment]
Thanks for your reply, what I have now is: RGB and Depth from the rgbd camera, and I have the bbox and gt_pose of the object in the RGB image.
